version: '3.9'

services:
  r6374:
    container_name: r6374
    image: redis/redis-stack:latest
    command: ["redis-server", "--requirepass", "key_admin", "--port", "6374", "--loadmodule", "/opt/redis-stack/lib/redisearch.so"]
    ports:
      - "6374:6374"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6374", "-a", "key_admin", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:  # Add the networks section
      - my_network  # Use the same network name as the first Docker Compose file

  hotmesh-dashboard:
    build:
      context: .
      target: development
    command: npm run service
    container_name: hotmesh-dashboard
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
    depends_on:
      r6374:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3010 || exit 1
      interval: 5s
      timeout: 4s
      retries: 50
    networks:  # Add the networks section
      - my_network  # Use the same network name as the first Docker Compose file

networks:  # Define the network at the bottom of the file
  my_network:
